### ISSUE TITLE
Incident retornando undefined

### ISSUE THREAD

**Issue by Aspheria** [josepholiveira/be-the-hero#2]
Mesmo realizando os procedimentos de npx knex migrate:rollback --all, exclusão do db.sqlite, e npx knex migrate:latest sigo retornando no erro:

@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@
undefined
{}
@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@
(node:4508) UnhandledPromiseRejectionWarning: Error: insert into incidents (description, ong_id, title, value) 
values (NULL, NULL, NULL, NULL) - SQLITE_CONSTRAINT: NOT NULL constraint failed: incidents.title
(node:4508) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:4508) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections 
that are not handled will terminate the Node.js process with a non-zero exit code.

![issue1](https://user-images.githubusercontent.com/53099585/77833452-3165ce80-711c-11ea-8cd4-7f5b05e4bedb.PNG)

![issue](https://user-images.githubusercontent.com/53099585/77833544-fb751a00-711c-11ea-991b-920011d3051c.PNG)

![issue2](https://user-images.githubusercontent.com/53099585/77833547-0334be80-711d-11ea-83ae-69ed875abb1f.PNG)
![issue3](https://user-images.githubusercontent.com/53099585/77833548-03cd5500-711d-11ea-9da4-6e48845da8d5.PNG)
![issue4](https://user-images.githubusercontent.com/53099585/77833550-03cd5500-711d-11ea-92c2-30331626cf32.PNG)

**Comment by Aspheria** [comment]
https://github.com/Aspheria/semana-dev``

**Comment by josepholiveira** [comment]
Opa @Aspheria !

Poderia tentar excluir sua request do insomnia e criar novamente?

Aparentemente isso é um problema com o insomnia não conseguindo enviar as informações corretamente.

Pra isso é só clicar com o botão direito, e clicar em DELETE duas vezes.

Lembrando que precisa criar do zero, não pode ser duplicando uma nova.

Espero que ajude!

**Comment by Aspheria** [comment]
Olá Joseph, obrigada pelo reply! 

Muitissímo obrigada, eu havia tentado refazer tudo, menos mexer nas requests do insomnia! 

Me ajudou muito, agora eu consigo dar segmento.
